/*Comprobamos que no exista la base de datos, y si existe la eliminamos.*/
DROP DATABASE IF EXISTS ONE_PIECE_SERRANO_JESUS;
/*Creamos la base de datos*/
CREATE DATABASE ONE_PIECE_SERRANO_JESUS;
/*Usamos la nueva base de datos*/
USE ONE_PIECE_SERRANO_JESUS;
/*Creamos las tablas*/
CREATE TABLE CAPITULO (
	ID_CAPITULO INT AUTO_INCREMENT,
    NUMERO_CAPITULO INT,
    TITULO VARCHAR(110) NOT NULL,
    ILUSTRADOR VARCHAR(110),
    PRIMARY KEY (ID_CAPITULO)
);
CREATE TABLE VISITA (
	ID_CAPITULO INT,
    ID_PELICULA INT,
    ID_LUGAR INT
);
CREATE TABLE LUGAR (
	ID_LUGAR INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    TIPO VARCHAR(110),
    DESCRIPCION VARCHAR(110),
    PRIMARY KEY (ID_LUGAR)
);
CREATE TABLE PELICULA(
	ID_PELICULA INT AUTO_INCREMENT,
    TITULO VARCHAR(110) NOT NULL,
    FECHA DATE,
    DURACION TIME,
    ILUSTRADOR VARCHAR(110),
    PRIMARY KEY (ID_PELICULA)
);
CREATE TABLE PERSONAJES_PELICULAS(
	ID_PERSONAJE INT,
    ID_PELICULA INT
);
CREATE TABLE PERSONAJE(
	ID_PERSONAJE INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    APODO VARCHAR(110) NOT NULL,
    RECOMPENSA FLOAT(20,2),
    PUESTO VARCHAR(110),
    RANGO varchar(110),
    CAPITAN INT,
    ID_BANDA INT,
    PRIMARY KEY (ID_PERSONAJE)
);
CREATE TABLE PERSONAJES_CAPITULOS(
	ID_PERSONAJE INT,
    ID_CAPITULO INT
);
CREATE TABLE BANDA(
	ID_BANDA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    CAPITAN INT,
    ID_BARCO INT,
    PRIMARY KEY (ID_BANDA)
);
CREATE TABLE ALIANZA_PIRATA(
	ID_BANDA1 INT,
    ID_BANDA2 INT
);
CREATE TABLE BARCO(
	ID_BARCO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    CAPACIDAD_MAX INT,
    PRIMARY KEY (ID_BARCO)
);

/*************************************************/
/*Introducimos las claves foraneas (foreign keys)*/
ALTER TABLE VISITA ADD CONSTRAINT capitulov_fk FOREIGN KEY (ID_CAPITULO) REFERENCES CAPITULO(ID_CAPITULO);
ALTER TABLE VISITA ADD CONSTRAINT peliculav_fk FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA);
ALTER TABLE VISITA ADD CONSTRAINT lugar_fk FOREIGN KEY (ID_LUGAR) REFERENCES LUGAR(ID_LUGAR);

ALTER TABLE PERSONAJES_PELICULAS ADD CONSTRAINT peliculap_fk FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA);
ALTER TABLE PERSONAJES_PELICULAS ADD CONSTRAINT personajep_fk FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE);

ALTER TABLE PERSONAJES_CAPITULOS ADD CONSTRAINT personajec_fk FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE);
ALTER TABLE PERSONAJES_CAPITULOS ADD CONSTRAINT capituloc_fk FOREIGN KEY (ID_CAPITULO) REFERENCES CAPITULO(ID_CAPITULO);

ALTER TABLE PERSONAJE ADD CONSTRAINT capitan_fk FOREIGN KEY (CAPITAN) REFERENCES PERSONAJE(ID_PERSONAJE) on update cascade;
ALTER TABLE PERSONAJE ADD CONSTRAINT bandap_fk FOREIGN KEY (ID_BANDA) REFERENCES BANDA(ID_BANDA) on update cascade;

ALTER TABLE ALIANZA_PIRATA ADD CONSTRAINT banda1_fk FOREIGN KEY (ID_BANDA1) REFERENCES BANDA(ID_BANDA);
ALTER TABLE ALIANZA_PIRATA ADD CONSTRAINT banda2_fk FOREIGN KEY (ID_BANDA2) REFERENCES BANDA(ID_BANDA);

ALTER TABLE BANDA ADD CONSTRAINT barco_fk FOREIGN KEY (ID_BARCO) REFERENCES BARCO(ID_BARCO);
