

-- Inserta los siguientes Datos


INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`BARCO` (`NOMBRE`, `CAPACIDAD_MAX`) VALUES ('Thousand Sunny', '11');
INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`BARCO` (`NOMBRE`, `CAPACIDAD_MAX`) VALUES ('Polar Tang', '6');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`BANDA` (`NOMBRE`) VALUES ('Piratas de Sombrero de Paja');
INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`BANDA` (`NOMBRE`) VALUES ('Piratas de Heart');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`CAPITULO` (`NUMERO_CAPITULO`, `TITULO`) VALUES ('1001', 'Luffy Sombrero de Paja');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PELICULA` (`TITULO`, `FECHA`) VALUES ('One Piece: Stampede', '2019-09-09');


INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Monkey D. Luffy', 'Sombrero de Paja', '2500000000', 'capitan', 'combatiente');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Roronoa Zoro', 'Cazador de Piratas', '330000000', 'comandante', 'combatiente');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Tony Chopper', 'El amante del algodon de azucar', '10000', 'tripulante', 'medico');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Trafalgar Law', 'El Cirujano de la Muerte', '500000000', 'capitan', 'combatiente');

INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Bepo', 'Doctor de la Muerte', '50000', 'comandante', 'navegante');


INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`) 
VALUES ('Vinsmoke Sanji', 'Pierna negra', '500000000');


INSERT INTO `ONE_PIECE_NOMRE_APELLIDO`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`) 
VALUES ('Portgas D. Ace', 'Puño de Fuego', '550000000');