/*MP02-UF2 1*/
/*Creació de la base de dades*/
CREATE DATABASE ONE_PIECE_SERRANO_JESUS;
/*Usem la nova base de dades*/
USE ONE_PIECE_SERRANO_JESUS;
/*CREEM LES TAULES*/
CREATE TABLE CAPITULO (
	ID_CAPITULO INT AUTO_INCREMENT,
    NUMERO_CAPITULO INT,
    TITULO VARCHAR(110) NOT NULL,
    ILUSTRADOR VARCHAR(110),
    PRIMARY KEY (ID_CAPITULO)
);
CREATE TABLE VISITA (
	ID_CAPITULO INT,
    ID_PELICULA INT,
    ID_LUGAR INT
);
CREATE TABLE LUGAR (
	ID_LUGAR INT,
    NOMBRE VARCHAR(110) NOT NULL,
    TIPO VARCHAR(110),
    DESCRIPCION VARCHAR(110),
    PRIMARY KEY (ID_LUGAR)
);
CREATE TABLE PELICULA(
	ID_PELICULA INT auto_increment,
    TITULO VARCHAR(110) NOT NULL,
    FECHA DATE,
    DURACION TIME,
    ILUSTRADOR VARCHAR(110),
    PRIMARY KEY (ID_PELICULA)
);
CREATE TABLE PERSONAJES_PELICULAS(
	ID_PERSONAJE INT,
    ID_PELICULA INT
);
CREATE TABLE PERSONAJE(
	ID_PERSONAJE INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    APODO VARCHAR(110) NOT NULL,
    RECOMPENSA FLOAT(20,2),
    PUESTO VARCHAR(110),
    RANGO varchar(110),
    CAPITAN INT,
    ID_BANDA INT,
    PRIMARY KEY (ID_PERSONAJE)
);
CREATE TABLE PERSONAJES_CAPITULOS(
	ID_PERSONAJE INT,
    ID_CAPITULO INT
);
CREATE TABLE BANDA(
	ID_BANDA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    CAPITAN INT,
    ID_BARCO INT,
    PRIMARY KEY (ID_BANDA)
);
CREATE TABLE ALIANZA_PIRATA(
	ID_BANDA1 INT,
    ID_BANDA2 INT
);
CREATE TABLE BARCO(
	ID_BARCO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(110) NOT NULL,
    CAPACIDAD_MAX INT,
    PRIMARY KEY (ID_BARCO)
);

/*Afegim les foreign keys*/
ALTER TABLE VISITA ADD CONSTRAINT capitulov_fk FOREIGN KEY (ID_CAPITULO) REFERENCES CAPITULO(ID_CAPITULO);
ALTER TABLE VISITA ADD CONSTRAINT peliculav_fk FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA);
ALTER TABLE VISITA ADD CONSTRAINT lugar_fk FOREIGN KEY (ID_LUGAR) REFERENCES LUGAR(ID_LUGAR);

ALTER TABLE PERSONAJES_PELICULAS ADD CONSTRAINT peliculap_fk FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA);
ALTER TABLE PERSONAJES_PELICULAS ADD CONSTRAINT personajep_fk FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE);

ALTER TABLE PERSONAJES_CAPITULOS ADD CONSTRAINT personajec_fk FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE);
ALTER TABLE PERSONAJES_CAPITULOS ADD CONSTRAINT capituloc_fk FOREIGN KEY (ID_CAPITULO) REFERENCES CAPITULO(ID_CAPITULO);

ALTER TABLE PERSONAJE ADD CONSTRAINT capitan_fk FOREIGN KEY (CAPITAN) REFERENCES PERSONAJE(ID_PERSONAJE) on update cascade;
ALTER TABLE PERSONAJE ADD CONSTRAINT bandap_fk FOREIGN KEY (ID_BANDA) REFERENCES BANDA(ID_BANDA) on update cascade;

ALTER TABLE ALIANZA_PIRATA ADD CONSTRAINT banda1_fk FOREIGN KEY (ID_BANDA1) REFERENCES BANDA(ID_BANDA);
ALTER TABLE ALIANZA_PIRATA ADD CONSTRAINT banda2_fk FOREIGN KEY (ID_BANDA2) REFERENCES BANDA(ID_BANDA);

ALTER TABLE BANDA ADD CONSTRAINT barco_fk FOREIGN KEY (ID_BARCO) REFERENCES BARCO(ID_BARCO);

/*Afegir les noves restriccions*/
/*1*/
ALTER TABLE PELICULA MODIFY FECHA DATE NOT NULL;
ALTER TABLE PERSONAJE MODIFY APODO VARCHAR(110) NOT NULL UNIQUE;

/*2*/
ALTER TABLE PELICULA MODIFY DURACION TIME DEFAULT "1:45:00";

/*3*/
ALTER TABLE PERSONAJE MODIFY PUESTO VARCHAR(50);
ALTER TABLE PERSONAJE ADD CONSTRAINT puesto_check CHECK (PUESTO IN ('combatiente', 'navegante', 'cocinero', 'médico', 'ingeniero'));

/*4*/
ALTER TABLE PERSONAJE ADD CONSTRAINT rango_check CHECK (RANGO IN ('capitan', 'comandante','tripulante'));
ALTER TABLE LUGAR ADD CONSTRAINT tipo_lugar_check CHECK (TIPO IN ('Isla', 'Ciudad', 'Barco', 'Base Militar'));

/*5*/
ALTER TABLE LUGAR ADD COLUMN REGION VARCHAR(110) CHECK (REGION IN ('North Blue' , 'South Blue' , 'East Blue' , 'West Blue'));








/*MP02-UF2 3*/
/*Relleno rápido*/
INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`BARCO` (`NOMBRE`, `CAPACIDAD_MAX`) VALUES ('Thousand Sunny', '11');
INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`BARCO` (`NOMBRE`, `CAPACIDAD_MAX`) VALUES ('Polar Tang', '6');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`BANDA` (`NOMBRE`) VALUES ('Piratas de Sombrero de Paja');
INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`BANDA` (`NOMBRE`) VALUES ('Piratas de Heart');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`CAPITULO` (`NUMERO_CAPITULO`, `TITULO`) VALUES ('1001', 'Luffy Sombrero de Paja');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PELICULA` (`TITULO`, `FECHA`) VALUES ('One Piece: Stampede', '2019-09-09');


INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Monkey D. Luffy', 'Sombrero de Paja', '2500000000', 'capitan', 'combatiente');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Roronoa Zoro', 'Cazador de Piratas', '330000000', 'comandante', 'combatiente');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Tony Chopper', 'El amante del algodon de azucar', '10000', 'tripulante', 'medico');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Trafalgar Law', 'El Cirujano de la Muerte', '500000000', 'capitan', 'combatiente');

INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`, `RANGO`,PUESTO) 
VALUES ('Bepo', 'Doctor de la Muerte', '50000', 'comandante', 'navegante');


INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`) 
VALUES ('Vinsmoke Sanji', 'Pierna negra', '500000000');


INSERT INTO `ONE_PIECE_SERRANO_JESUS`.`PERSONAJE` (`NOMBRE`, `APODO`, `RECOMPENSA`) 
VALUES ('Portgas D. Ace', 'Puño de Fuego', '550000000');

/*1*/
UPDATE BANDA SET ID_BARCO = (SELECT ID_BARCO FROM BARCO WHERE NOMBRE = 'Thousand Sunny') WHERE BANDA.NOMBRE LIKE '%Sombrero de Paja%';
UPDATE BANDA SET ID_BARCO = (SELECT ID_BARCO FROM BARCO WHERE NOMBRE = 'Polar Tang') WHERE BANDA.NOMBRE = 'Piratas de Heart';

/*2*/
INSERT INTO BANDA (NOMBRE) VALUES ('Los piratas de Shirohige');
INSERT INTO ALIANZA_PIRATA
SET ID_BANDA1 = (SELECT ID_BANDA
		FROM BANDA
		WHERE NOMBRE = 'Piratas de Sombrero de Paja'),
	ID_BANDA2 = (SELECT ID_BANDA
		FROM BANDA
		WHERE NOMBRE = 'Los piratas de Shirohige');

/*3*/
UPDATE PERSONAJE
SET ID_BANDA =(SELECT ID_BANDA
	       FROM BANDA
               WHERE NOMBRE = 'Piratas de Sombrero de Paja')
WHERE NOMBRE IN ('Monkey D. Luffy','Roronoa Zoro','Vinsmoke Sanji');

/*4*/
UPDATE PERSONAJE
SET PUESTO = 'medico', ID_BANDA = (SELECT ID_BANDA
				   FROM BANDA
				   WHERE NOMBRE = 'Piratas de Heart')
WHERE NOMBRE = 'Bepo';

/*5*/
DELETE FROM PERSONAJE
WHERE PUESTO IS NULL AND ID_BANDA IS NULL;


/*6*/
UPDATE BANDA
SET CAPITAN =(SELECT ID_PERSONAJE
	       FROM PERSONAJE
               WHERE NOMBRE = 'Monkey D. Luffy')
WHERE ID_BANDA = (SELECT ID_BANDA FROM PERSONAJE WHERE NOMBRE = 'Monkey D. Luffy');

UPDATE PERSONAJE
SET CAPITAN =(SELECT ID_PERSONAJE WHERE NOMBRE like 'Monkey D. Luffy')
WHERE ID_BANDA = 1;

select * from PERSONAJE where id_banda = 1;

/*MP02-UF2 4*/
/*Consultes sobre Chinook*/
SELECT t.Name, g.Name
FROM InvoiceLine il
INNER JOIN Track t ON il.TrackId = t.TrackId
INNER JOIN Invoice i ON il.InvoiceId = i.InvoiceId
INNER JOIN Genre g ON t.GenreId = g.GenreId
WHERE i.CustomerId = (
						SELECT CustomerId
                        FROM Customer 
                        WHERE FirstName = "Camille" 
                        AND LastName = "Bernard"
                        );

SELECT g.Name, count(g.GenreId) AS 'Cant.'
FROM InvoiceLine il
INNER JOIN Track t ON il.TrackId = t.TrackId
INNER JOIN Invoice i ON il.InvoiceId = i.InvoiceId
INNER JOIN Genre g ON t.GenreId = g.GenreId
WHERE i.CustomerId = (
						SELECT CustomerId
                        FROM Customer 
                        WHERE FirstName = "Camille" 
                        AND LastName = "Bernard"
                        )
GROUP BY g.GenreId;

SELECT Name, sum(Quantity)
FROM InvoiceLine il 
INNER JOIN Track t ON il.TrackId = t.TrackId
GROUP BY il.TrackId;

SELECT Name, (milliseconds/60000) AS 'Minutes' from Track WHERE composer = 'Johann Sebastian Bach';

SELECT ar.Name AS 'Artist Name', t.Name AS 'Track Name'
FROM Track t, Artist ar
WHERE ar.Name like t.name AND ar.Name != t.Composer;

